language: ruby
rvm:
 - 2.3.3

before_script:
  - psql -c 'create database picterest_test;' -U postgres

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: picterest-test
  on:
    repo: igorbezsmertnyi/picterest
