# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6d1ee77cec7ab35650f6600491d0c05ed3ce0b1ba3db3c2085bd2a4820923202fd7da1070842b49ca1fef914c5e632cd56306453de42f413fa719ab681fd3b1

test:
  secret_key_base: 623b572446bced97511f9c38c73296680bf558f9cad33ff0ec8907d5416b607cff79f283340639d8a19931df03f17e39b6b28f6dc99c43088df376fdbf79e163

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
